// <auto-generated />
using System;
using MediLaboSolutions.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediLaboSolutions.API.Migrations
{
    [DbContext(typeof(MediLaboSolutionsDbContext))]
    [Migration("20250512111051_AjoutTableAdresse")]
    partial class AjoutTableAdresse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediLaboSolutions.API.Models.Patient.AdresseEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodePostal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Pays")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ville")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Voie")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("MediLaboSolutions.API.Models.Patient.PatientEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdresseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Genre")
                        .HasColumnType("tinyint");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("Telephone")
                        .HasMaxLength(10)
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AdresseId")
                        .IsUnique()
                        .HasFilter("[AdresseId] IS NOT NULL");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MediLaboSolutions.API.Models.Patient.PatientEF", b =>
                {
                    b.HasOne("MediLaboSolutions.API.Models.Patient.AdresseEF", "Adresse")
                        .WithOne()
                        .HasForeignKey("MediLaboSolutions.API.Models.Patient.PatientEF", "AdresseId");

                    b.Navigation("Adresse");
                });
#pragma warning restore 612, 618
        }
    }
}
